title: "Portofolio Samuel"
description: "Website portofolio saya"
baseurl: "" # jika repo-nya bernama username.github.io, kosongkan
url: "https://ch1ns0n.github.io" # ganti dengan URL GitHub Pages kamu

theme: "minimal-mistakes-jekyll"

plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/minimal-mistakes

# opsional
minimal_mistakes_skin: default