title: "Samuel Chinson"
name: "Samuel Chinson"
email: "samuel.chinson@gmail.com"
description: >-
  Data Analyst Portfolio

url: "https://samuelchinson.github.io"
baseurl: ""

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Navigation
navigation:
  - title: "About"
    url: /about/
  - title: "Portfolio"
    url: /portfolio/
  - title: "Resume"
    url: /resume/

# Footer
author:
  name   : "Samuel Chinson"
  email  : "samuel.chinson@gmail.com"
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/samuelchinson/"
