title: "clucker.blog"
name: "정성호"
description: "기술 블로그 - 개발 지식 정리 및 기록"
url: "https://clucker12.github.io"
baseurl: ""
repository: "clucker12/clucker12.github.io"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

author:
  name: "정성호"
  bio: "Backend Developer. 기술을 기록하고 공유합니다."
  location: "Seoul, Korea"
  email: "412jsh@naver.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/clucker12"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:412jsh@naver.com"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: false
      share: true
      show_date: true
      show_categories: false
      show_tags: false

  - scope:
      path: "_pages/category"
      type: "pages"
    values:
      layout: category
      author_profile: true
      show_date: true

# ✅ SEO Related
google_site_verification: ""
bing_site_verification: ""
yandex_site_verification: ""
naver_site_verification: "54d11364c73ed7869ad0d22c83f6f2450007bddc"

date_format: "%Y-%m-%d"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag:  /tags/:name/

category_archive:
  type: liquid
  path: /categories/

# ✅ navigation에 카테고리 추가
navigation:
  - title: "카테고리"
    url: /categories/

# ✅ _pages 폴더를 컬렉션으로 인식
collections:
  pages:
    output: true
    permalink: /:path/

markdown: kramdown
highlighter: rouge

permalink: /:categories/:title/
timezone: Asia/Seoul

sass:
  sass_dir: _sass
  style: compressed

compress_html:
  clippings: all
  ignore:
    envs: development

paginate: 5
paginate_path: /page:num/

search: true
search_full_content: true

# ✅ _pages 폴더 포함
include:
  - _pages

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
