title: "Portofolio Samuel"
description: "Selamat datang di portofolio saya"
baseurl: "" 
url: "https://samuelchinson.github.io"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme

minimal_mistakes_skin: "default"
